### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by saintajax33** [AndrewNeo/faextender-chrome#12]
The latest update broke everything... 

Auto downloads aren't working, the setting appears to be gone. 

I can't open the folders attached to an artists gallery.

When I attempt to change the save location to my pictures, it dumps everything to downloads instead and makes a new pictures directory. 

Is this what the app is going to be like from now on?

**Comment by AndrewNeo** [comment]
Assuming you're talking about the Firefox version of the extension, Mozilla moved from the classic extension style (old FAExtender) to WebExtensions (the Chrome model). This means we're [restricted by what its downloads API can do](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/downloads/download), instead of being able to blindly access the filesystem.

* Auto downloads are possible, but without a "don't write if it exists" option there will be a LOT of duplicate downloads.
* There is a subdirectory setting available to not drop it in the root of the downloads directory.

**Comment by saintajax33** [comment]
I'd be okay with duplicate downloads to save time, I get over 1000 submissions a day, and going through them by hand and hitting download on each would be a drag. But I understand why you would decide to get rid of that. 

So is there a way to change the file path to save in pictures instead of downloads? I have programs that empty my download folder automatically, so saving anything in there really isn't an option.

**Comment by AndrewNeo** [comment]
You can save in a subdirectory of downloads but it is a browser restriction that it has to be the downloads directory.
